# Generated by Django 4.2.5 on 2023-09-17 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("predict", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="homes",
            name="baths",
            field=models.DecimalField(decimal_places=1, default=None, max_digits=4),
        ),
        migrations.AddField(
            model_name="homes",
            name="beds",
            field=models.IntegerField(default=None, max_length=2),
        ),
        migrations.AddField(
            model_name="homes",
            name="garages",
            field=models.IntegerField(default=None, max_length=2),
        ),
        migrations.AddField(
            model_name="homes",
            name="lot_sqft",
            field=models.IntegerField(default=None, max_length=6),
        ),
        migrations.AddField(
            model_name="homes",
            name="price",
            field=models.IntegerField(default=None, max_length=9),
        ),
        migrations.AddField(
            model_name="homes",
            name="square_feet",
            field=models.IntegerField(default=None, max_length=5),
        ),
        migrations.AddField(
            model_name="homes",
            name="year_built",
            field=models.IntegerField(default=None, max_length=4),
        ),
    ]
