# Generated by Django 4.2.5 on 2023-09-17 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "predict",
            "0002_homes_baths_homes_beds_homes_garages_homes_lot_sqft_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="homes",
            name="baths",
            field=models.DecimalField(
                decimal_places=1, default=None, max_digits=4, verbose_name="Baths"
            ),
        ),
        migrations.AlterField(
            model_name="homes",
            name="beds",
            field=models.IntegerField(default=None, max_length=2, verbose_name="Beds"),
        ),
        migrations.AlterField(
            model_name="homes",
            name="garages",
            field=models.IntegerField(
                default=None, max_length=2, verbose_name="Garages"
            ),
        ),
        migrations.AlterField(
            model_name="homes",
            name="lot_sqft",
            field=models.IntegerField(
                default=None, max_length=6, verbose_name="Lot_SqFt"
            ),
        ),
        migrations.AlterField(
            model_name="homes",
            name="price",
            field=models.IntegerField(default=None, max_length=9, verbose_name="Price"),
        ),
        migrations.AlterField(
            model_name="homes",
            name="square_feet",
            field=models.IntegerField(
                default=None, max_length=5, verbose_name="Square_Feet"
            ),
        ),
        migrations.AlterField(
            model_name="homes",
            name="year_built",
            field=models.IntegerField(
                default=None, max_length=4, verbose_name="Year_Built"
            ),
        ),
    ]
