# Generated by Django 4.2.5 on 2023-09-17 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("predict", "0003_alter_homes_baths_alter_homes_beds_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="homes",
            name="beds",
            field=models.IntegerField(default=None, verbose_name="Beds"),
        ),
        migrations.AlterField(
            model_name="homes",
            name="garages",
            field=models.IntegerField(default=None, verbose_name="Garages"),
        ),
        migrations.AlterField(
            model_name="homes",
            name="lot_sqft",
            field=models.IntegerField(default=None, verbose_name="Lot_SqFt"),
        ),
        migrations.AlterField(
            model_name="homes",
            name="price",
            field=models.IntegerField(default=None, verbose_name="Price"),
        ),
        migrations.AlterField(
            model_name="homes",
            name="square_feet",
            field=models.IntegerField(default=None, verbose_name="Square_Feet"),
        ),
        migrations.AlterField(
            model_name="homes",
            name="year_built",
            field=models.IntegerField(default=None, verbose_name="Year_Built"),
        ),
    ]
