# Generated by Django 4.2.5 on 2023-09-18 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("predict", "0004_alter_homes_beds_alter_homes_garages_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Saved",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("price", models.IntegerField(default=None, verbose_name="Price")),
                (
                    "baths",
                    models.DecimalField(
                        decimal_places=1,
                        default=None,
                        max_digits=4,
                        verbose_name="Baths",
                    ),
                ),
                ("beds", models.IntegerField(default=None, verbose_name="Beds")),
                (
                    "square_feet",
                    models.IntegerField(default=None, verbose_name="Square_Feet"),
                ),
                (
                    "year_built",
                    models.IntegerField(default=None, verbose_name="Year_Built"),
                ),
                ("garages", models.IntegerField(default=None, verbose_name="Garages")),
                (
                    "lot_sqft",
                    models.IntegerField(default=None, verbose_name="Lot_SqFt"),
                ),
            ],
        ),
    ]
