# Generated by Django 4.2.5 on 2023-09-26 23:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("predict", "0005_saved"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Saved",
        ),
    ]
